# -*- mode: makefile; -*-

BOOST_DIR = /usr/local

BOOST_INCDIR = $(BOOST_DIR)/include
BOOST_LIBDIR = $(BOOST_DIR)/lib

BOOST_CPPFLAGS = -I$(BOOST_INCDIR)
BOOST_LDFLAGS  = -L$(BOOST_LIBDIR)

BOOST_LIBS =									\
    -lboost_log -lboost_log_setup				\
    -lboost_thread								\
    -lBoost_system

RANGE_DIR = /usr/local
RANGE_INCDIR = $(RANGE_DIR)/include
RANGE_CPPFLAGS = -I$(RANGE_INCDIR)

libavcodec_CPPFLAGS    = $(shell pkg-config --cflags libavcodec)
libavdevice_CPPFLAGS   = $(shell pkg-config --cflags libavdevice)
libavfilter_CPPFLAGS   = $(shell pkg-config --cflags libavfilter)
libavformat_CPPFLAGS   = $(shell pkg-config --cflags libavformat)
libavutil_CPPFLAGS     = $(shell pkg-config --cflags libavutil)
libpostproc_CPPFLAGS   = $(shell pkg-config --cflags libpostproc)
libswresample_CPPFLAGS = $(shell pkg-config --cflags libswresample)
libswscale_CPPFLAGS    = $(shell pkg-config --cflags libswscale)

FFMPEG_CPPFLAGS =								\
    $(libavcodec_CPPFLAGS)						\
    $(libavdevice_CPPFLAGS)						\
    $(libavfilter_CPPFLAGS)						\
    $(libavformat_CPPFLAGS)						\
    $(libavutil_CPPFLAGS)						\
    $(libpostproc_CPPFLAGS)						\
    $(libswresample_CPPFLAGS)					\
    $(libswscale_CPPFLAGS)

JSONCPP_CPPFLAGS = $(shell pkg-config --cflags jsoncpp)
OPENAL_CPPFLAGS  = $(shell pkg-config --cflags openal)
SDL2_CPPFLAGS    = $(shell pkg-config --cflags sdl2)
LIBJPEG_CPPFLAGS = $(shell pkg-config --cflags libjpeg)
LIBPNG_CPPFLAGS  = $(shell pkg-config --cflags libpng)

libavcodec_LDFLAGS    = $(shell pkg-config --libs libavcodec)
libavdevice_LDFLAGS   = $(shell pkg-config --libs libavdevice)
libavfilter_LDFLAGS   = $(shell pkg-config --libs libavfilter)
libavformat_LDFLAGS   = $(shell pkg-config --libs libavformat)
libavutil_LDFLAGS     = $(shell pkg-config --libs libavutil)
libpostproc_LDFLAGS   = $(shell pkg-config --libs libpostproc)
libswresample_LDFLAGS = $(shell pkg-config --libs libswresample)
libswscale_LDFLAGS    = $(shell pkg-config --libs libswscale)

FFMPEG_LDFLAGS =								\
    $(libavcodec_LDFLAGS)						\
    $(libavdevice_LDFLAGS)						\
    $(libavfilter_LDFLAGS)						\
    $(libavformat_LDFLAGS)						\
    $(libavutil_LDFLAGS)						\
    $(libpostproc_LDFLAGS)						\
    $(libswresample_LDFLAGS)					\
    $(libswscale_LDFLAGS)

JSONCPP_LDFLAGS = $(shell pkg-config --libs jsoncpp)
OPENAL_LDFLAGS  = $(shell pkg-config --libs openal)
SDL2_LDFLAGS    = $(shell pkg-config --libs sdl2)
LIBJPEG_LDFLAGS = $(shell pkg-config --libs libjpeg)
LIBPNG_LDFLAGS  = $(shell pkg-config --libs libpng)

CPPFLAGS = -I.									\
    $(BOOST_CPPFLAGS)							\
    $(RANGE_CPPFLAGS)							\
    $(FFMPEG_CPPFLAGS)							\
    $(JSONCPP_CPPFLAGS)							\
    $(OPENAL_CPPFLAGS)							\
    $(SDL2_CPPFLAGS)							\
    $(LIBJPEG_CPPFLAGS)							\
    $(LIBPNG_CPPFLAGS)

LDFLAGS =										\
    $(BOOST_LDFLAGS)							\
    $(RANGE_LDFLAGS)							\
    $(FFMPEG_LDFLAGS)							\
    $(JSONCPP_LDFLAGS)							\
    $(OPENAL_LDFLAGS)							\
    $(SDL2_LDFLAGS)								\
    $(LIBJPEG_LDFLAGS)							\
    $(LIBPNG_LDFLAGS)

LIBS = $(BOOST_LIBS)

